### ISSUE TITLE
SDDM won't start due to an issue with PAM

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-Kattleya/plasma-image#10]
![image](https://github.com/Vanilla-Kattleya/plasma-image/assets/9479903/a766acdb-a2b8-443b-87b3-20e9e5b0cb9e)

Re-installing SDDM manually fix the problem, looks like the image is missing some dependencies.

**Comment by dominichayesferen** [comment]
Your image appears to dictate a lack of required `sddm` user generation, more-so.

**Comment by mirkobrombin** [comment]
> Your image appears to dictate a lack of required `sddm` user generation, more-so.

SDDM requires a specific user?

**Comment by Maxwelldoug** [comment]
This was fixed at some point before #20 was forked, so I recommend it be closed.
